services:
  - type: web
    name: ups-prl-service
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 2 -b 0.0.0.0:$PORT app:app"
    envVars:
      - key: UPS_CLIENT_ID
        sync: false
      - key: UPS_CLIENT_SECRET
        sync: false
      - key: UPS_SHIPPER_NUMBER
        value: "1Y703V"
      - key: UPS_PROMO_CODE
        value: "EIGSHIPSUPS"